### ISSUE TITLE
Seg faults when taking a trip from Boulder to Seattle

### ISSUE THREAD

**Issue by christyroney** [LoganConnor/Thompson_CSCI2270_FinalProject#1]
When planning a trip from Boulder to Seattle, this code seg faults.  Also, when planning a trip and picking out the car I accidently typed in 100 instead of 10 which caused the code to segfault since there was no car of option 100.

**Comment by ermontross** [comment]
It seems to only happen if you do Seattle then Boulder twice. It did not segfault for me the first time, only if you do it two times in the same run.

**Comment by christyroney** [comment]
Oh yes you're right it doesn't seg fault for Seattle to Boulder, however it does seg fault when going from Boulder to Seattle.

**Comment by LoganConnor** [comment]
We found the bug and solved it. Please let us know if it seg faults again, but it should be solved now.

**Comment by christyroney** [comment]
Okay awesome!
