### ISSUE TITLE
Just a print out issue

### ISSUE THREAD

**Issue by schubydooo** [LoganConnor/Thompson_CSCI2270_FinalProject#4]
After selecting main menu option 3, and giving it an appropriate number for hours to travel, if you misspell the name of the city there are approximately 30 printouts of "One or more of the cities doesn't exist".  
Code continues to run after as expected, so its really just a printing issue.

**Comment by LoganConnor** [comment]
Thanks for finding that, I corrected the code to check for an invalid entry. Thanks!
